environment:
  matrix:
  - JULIAVERSION: "julialang/bin/winnt/x86/0.6/julia-0.6-latest-win32.exe"
  - JULIAVERSION: "julialang/bin/winnt/x64/0.6/julia-0.6-latest-win64.exe"

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile(
        $("http://s3.amazonaws.com/"+$env:JULIAVERSION),
        "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/helgee/Convertible.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/helgee/RemoteFiles.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/helgee/OptionalData.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/helgee/EarthOrientation.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/JuliaAstrodynamics/AstronomicalTime.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/JuliaAstrodynamics/AstroDynBase.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/JuliaAstrodynamics/JPLEphemeris.jl.git\"); Pkg.build(\"SPICE\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/JuliaAstrodynamics/SPICE.jl.git\"); Pkg.build(\"SPICE\")"
  - C:\projects\julia\bin\julia -e "versioninfo();
      Pkg.clone(pwd(), \"AstroDynCoordinates\"); Pkg.build(\"AstroDynCoordinates\")"

test_script:
  - C:\projects\julia\bin\julia -e "Pkg.test(\"AstroDynCoordinates\")"
