name: CompatHelper

on:
  schedule:
    - cron: '00 00 */4 * *'

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - name: Install CompatHelper
        shell: julia --color=yes {0}
        run: using Pkg; Pkg.add("CompatHelper")
      - name: Run CompatHelper
        shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: using CompatHelper; CompatHelper.main()
